# Generated by Django 5.1.1 on 2024-09-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zooloski', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupnaposjeta',
            options={'verbose_name': 'Grupna posjeta', 'verbose_name_plural': 'Grupne posjete'},
        ),
        migrations.AlterModelOptions(
            name='kalendarrada',
            options={'verbose_name_plural': 'Kalendar rada'},
        ),
        migrations.AlterModelOptions(
            name='nastamba',
            options={'verbose_name': 'Nastamba', 'verbose_name_plural': 'Nastambe'},
        ),
        migrations.AlterModelOptions(
            name='nezgoda',
            options={'verbose_name': 'Nezgoda', 'verbose_name_plural': 'Nezgode'},
        ),
        migrations.AlterModelOptions(
            name='obaveza',
            options={'verbose_name': 'Obaveza', 'verbose_name_plural': 'Obveze'},
        ),
        migrations.AlterModelOptions(
            name='radnik',
            options={'verbose_name': 'Radnik', 'verbose_name_plural': 'Radnici'},
        ),
        migrations.AlterModelOptions(
            name='trosak',
            options={'verbose_name': 'Trosak', 'verbose_name_plural': 'Troskovi'},
        ),
        migrations.AlterModelOptions(
            name='zivotinja',
            options={'verbose_name': 'Zivotinja', 'verbose_name_plural': 'Zivotinje'},
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Zadatak',
        ),
    ]
